global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
 
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:3000"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:3001"]
