global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
 
scrape_configs:
  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:3000"]
 
  - job_name: "payment-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["payment-service:3001"]